server:
  port: 8081

spring:
  application:
    name: calendar
  datasource:
    url: jdbc:h2:mem:mydb
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate: ddl-auto
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
